#cloud-config
package_update: true
packages:
  - ca-certificates
  - wget
  - net-tools
  - gnupg
  - dnsmasq
  - dnsutils

write_files:
  - path: /etc/systemd/resolved.conf.d/dnsstub.conf
    content: |
      [Resolve]
      DNSStubListener=no
  - path: /etc/dnsmasq.d/azure.conf
    content: |
      interface=lo
      interface=tun*
      interface=as0t*
      bind-interfaces
      server=/corp.internal/168.63.129.16

runcmd:
  - systemctl restart systemd-resolved
  - wget -qO - https://as-repository.openvpn.net/as-repo-public.gpg | apt-key add -
  - echo "deb http://as-repository.openvpn.net/as/debian bullseye main" > /etc/apt/sources.list.d/openvpn-as-repo.list
  - apt-get update
  - apt-get install -y openvpn-as
  - echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
  - sysctl -p
  - systemctl enable dnsmasq
  - systemctl restart dnsmasq